### ISSUE TITLE
[feature] enhance exec steps

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-akromio#197]
### Please, describe the feature.

The exec steps should be enhanced as follows:

```yaml
# exec
- exec redis-cli ping
- run: redis-cli ping

# exec sudo
- exec sudo docker run ...
- sudo: docker run ...
```

### Please, describe what problem solving.

This is some similar to GitHub Actions, trying to reduce the errors when the user goes from this platform.
