### ISSUE TITLE
[feature] add dataset to group on job catalogs

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-akromio#206]
### Please, describe the feature.

Roght now, when we define a group on a job catalog, we have something as follows:

```yaml
- group: name
  jobs:
    # ...
```

If some local datum is shared by several jobs, these must be defined on every job.

The idea is be able to define shared data to group level:

```yaml
- group: group-name
  dataset:
    # data shared by its jobs
  jobs:
    # ...
```

### Please, describe what problem solving.

If we implement this, we are enhancing our productivity and reducing possible errors on shared data.
