### ISSUE TITLE
[feature] update plugin support

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-akromio#219]
### Please, describe the feature.

Right now, we use a plugin as follows:

```yaml
plugins:
  - plugin: package-name
    name: instance-name
    ini: arguments
```

It seems better the following:

```yaml
plugins:
  - plugin: instance-name
    impl: package-name
    ini: arguments
```

### Please, describe what problem solving.

When we create a datum or a job, the value associated is the item name. With the current implementation, this is different.
We have to be consistent and to try doing with a similar way.
