### ISSUE TITLE
[feature] data must suport merge property

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-akromio#230]
### Please, describe the feature.

If a (var or const) datum has a **merge** property, its value must be merged when initialized. Example:

```yaml
- const: d1
  value:
    x: 1
    z: 3

- const: d2
  value: $(d1)
  merge:
    y: 2
```

So, we have *d1* equal to *{x: 1, z: 3}*; and *d2*, *{x: 1, y: 2, z: 3}*.

### Please, describe what problem solving.

Ease the reuse of a previous datum with additional properties.
