### ISSUE TITLE
[bug] prepend and append aren't evaluated in the datasets

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-akromio#246]
### Package name and version

@akromio/dataset

### Environment

```bash
$ gattuso s
gattuso: v0.21.0
OS: linux (5.15.0-60-generic) #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023
Arch: x64
Node.js: v18.9.0
```

### Describe the bug

When a datum is defined with a prepend or append and this contains an expression, this is not evaluated.
Example:

```yaml
  - const: pageQ
    desc: Questions for building a content page.
    tags: [hidden, questions]
    prepend:
      - $(websiteDir)
      - input: pageDir
        title: Directory where to create the page in website dir
        defaultValue: /
      - input: fileName
    value: $(frontMatterQ)
```

Here, the value is evaluated but not its prepend: `$(websiteDir)`.

### Expected behavior

The prepend must be evaluated.

### Actual behavior

The prepend is not being evaluated.
